import React, { useState } from 'react'
import { FileText, Download, CheckCheck } from 'lucide-react'
import { exportSummaryAsPdf } from '../../utils/pdf'

interface ExportPanelProps {
  summary: string
  translatedSummary: string
  translatedLang: string
  pageTitle: string
  pageUrl: string
}

export default function ExportPanel({
  summary,
  translatedSummary,
  translatedLang,
  pageTitle,
  pageUrl,
}: ExportPanelProps) {
  const [exporting, setExporting] = useState(false)
  const [copied, setCopied] = useState(false)

  if (!summary) return null

  function copyText(text: string): Promise<void> {
    if (navigator.clipboard?.writeText) {
      return navigator.clipboard.writeText(text).catch(() => fallbackCopy(text))
    }
    return fallbackCopy(text)
  }

  function fallbackCopy(text: string): Promise<void> {
    return new Promise((resolve, reject) => {
      const ta = document.createElement('textarea')
      ta.value = text
      ta.style.cssText = 'position:fixed;left:-9999px;top:-9999px;opacity:0'
      document.body.appendChild(ta)
      ta.select()
      try { document.execCommand('copy'); resolve() }
      catch (e) { reject(e) }
      finally { document.body.removeChild(ta) }
    })
  }

  function handleCopyMarkdown() {
    let md = `# ${pageTitle}\n\n${summary}\n\n---\nSource: ${pageUrl}\nGenerated by WebGist`

    if (translatedSummary) {
      md += `\n\n## Translation (${translatedLang})\n\n${translatedSummary}`
    }

    copyText(md).then(() => {
      setCopied(true)
      setTimeout(() => setCopied(false), 2000)
    })
  }

  async function handleExport() {
    setExporting(true)
    try {
      exportSummaryAsPdf({
        title: pageTitle,
        url: pageUrl,
        summary,
        translated: translatedSummary || undefined,
        translatedLang: translatedLang || undefined,
      })
    } catch (err) {
      console.error('PDF export failed:', err)
    } finally {
      setTimeout(() => setExporting(false), 1500)
    }
  }

  return (
    <div className="px-4 pb-4">
      <div className="bg-gray-800/40 border border-gray-700/40 rounded-lg p-3">
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-2">
            <FileText size={14} className="text-indigo-400" />
            <p className="text-gray-300 text-xs font-medium">Export Summary</p>
          </div>

          <div className="flex items-center gap-2">
          <button
            onClick={handleCopyMarkdown}
            disabled={copied}
            className={`
              flex items-center gap-1.5 px-3 py-1.5 rounded-md text-xs font-medium transition-all flex-shrink-0
              ${copied
                ? 'bg-emerald-800/60 text-emerald-200 cursor-not-allowed'
                : 'bg-gray-700 hover:bg-gray-600 text-white'
              }
            `}
          >
            {copied ? (
              <>
                <CheckCheck size={13} className="text-emerald-400" />
                <span className="text-emerald-400">Copied!</span>
              </>
            ) : (
              <>
                <FileText size={13} />
                Markdown
              </>
            )}
          </button>

          <button
            onClick={handleExport}
            disabled={exporting}
            className={`
              flex items-center gap-1.5 px-3 py-1.5 rounded-md text-xs font-medium transition-all flex-shrink-0
              ${exporting
                ? 'bg-indigo-800/60 text-indigo-200 cursor-not-allowed'
                : 'bg-indigo-700 hover:bg-indigo-600 text-white'
              }
            `}
          >
            {exporting ? (
              <>
                <span className="w-3 h-3 border-2 border-indigo-300/30 border-t-indigo-200 rounded-full animate-spin" />
                Opening...
              </>
            ) : (
              <>
                <Download size={13} />
                Download
              </>
            )}
          </button>
          </div>
        </div>
      </div>
    </div>
  )
}
