import React from 'react'
import {
  Sparkles, ScrollText, AlertCircle, Copy, CheckCheck,
  Bookmark, BookmarkCheck, Clock, Layers, RefreshCw,
  Plus, X, FileText, ArrowLeftRight,
} from 'lucide-react'
import { useState } from 'react'
import { CustomPrompt } from '../../utils/storage'

type Status = 'idle' | 'loading' | 'streaming' | 'done' | 'error'

export const SUMMARY_MODES = [
  { id: 'keypoints', label: 'Key Points' },
  { id: 'brief',     label: 'Brief'      },
  { id: 'eli5',      label: 'ELI5'       },
  { id: 'actions',   label: 'Actions'    },
  { id: 'proscons',  label: 'Pros & Cons'},
] as const

export type SummaryMode = typeof SUMMARY_MODES[number]['id']

interface SummaryPanelProps {
  summary: string
  prevSummary: string
  status: Status
  errorMessage: string
  hasApiKey: boolean
  isSaved: boolean
  isCached: boolean
  isExtracting?: boolean
  customPrompts: CustomPrompt[]
  summaryLength: 'short' | 'medium' | 'long'
  pageTitle: string
  pageUrl: string
  onSummarize: (mode: string) => void
  onExtractPage: () => void
  onMultiTab: () => void
  onSave: () => void
  onResync: () => void
  onLengthChange: (len: 'short' | 'medium' | 'long') => void
  onCustomPromptsChange: (prompts: CustomPrompt[]) => void
}

const LENGTH_OPTIONS: { id: 'short' | 'medium' | 'long'; label: string }[] = [
  { id: 'short',  label: 'Short'  },
  { id: 'medium', label: 'Medium' },
  { id: 'long',   label: 'Long'   },
]

function readingTime(text: string): string {
  const words = text.trim().split(/\s+/).length
  const mins = Math.ceil(words / 200)
  return `~${mins} min read`
}

export default function SummaryPanel({
  summary,
  prevSummary,
  status,
  errorMessage,
  hasApiKey,
  isSaved,
  isCached,
  isExtracting = false,
  customPrompts,
  summaryLength,
  pageTitle,
  pageUrl,
  onSummarize,
  onExtractPage,
  onMultiTab,
  onSave,
  onResync,
  onLengthChange,
  onCustomPromptsChange,
}: SummaryPanelProps) {
  const [copied, setCopied] = useState(false)
  const [copiedMd, setCopiedMd] = useState(false)
  const [mode, setMode] = useState<string>('keypoints')
  const [showAddPrompt, setShowAddPrompt] = useState(false)
  const [newLabel, setNewLabel] = useState('')
  const [newPromptText, setNewPromptText] = useState('')
  const [showCompare, setShowCompare] = useState(false)

  function copyToClipboard(text: string): Promise<void> {
    // Try modern clipboard API first, fall back to execCommand for iframe contexts
    if (navigator.clipboard?.writeText) {
      return navigator.clipboard.writeText(text).catch(() => execCommandCopy(text))
    }
    return execCommandCopy(text)
  }

  function execCommandCopy(text: string): Promise<void> {
    return new Promise((resolve, reject) => {
      const ta = document.createElement('textarea')
      ta.value = text
      ta.style.cssText = 'position:fixed;left:-9999px;top:-9999px;opacity:0'
      document.body.appendChild(ta)
      ta.select()
      try {
        document.execCommand('copy')
        resolve()
      } catch (e) {
        reject(e)
      } finally {
        document.body.removeChild(ta)
      }
    })
  }

  function handleCopy() {
    if (!summary) return
    copyToClipboard(summary).then(() => {
      setCopied(true)
      setTimeout(() => setCopied(false), 2000)
    })
  }

  function handleCopyMd() {
    if (!summary) return
    let md = `# ${pageTitle || 'Summary'}\n\n${summary}`
    if (pageUrl) md += `\n\n---\nSource: ${pageUrl}`
    md += `\nGenerated by WebGist`
    copyToClipboard(md).then(() => {
      setCopiedMd(true)
      setTimeout(() => setCopiedMd(false), 2000)
    })
  }

  function handleAddCustomPrompt() {
    if (!newLabel.trim() || !newPromptText.trim()) return
    const prompt: CustomPrompt = {
      id: `custom_${Date.now()}`,
      label: newLabel.trim(),
      prompt: newPromptText.trim(),
    }
    onCustomPromptsChange([...customPrompts, prompt])
    setNewLabel('')
    setNewPromptText('')
    setShowAddPrompt(false)
  }

  function handleDeleteCustomPrompt(id: string) {
    onCustomPromptsChange(customPrompts.filter(p => p.id !== id))
    if (mode === id) setMode('keypoints')
  }

  const isLoading = status === 'loading'
  const isStreaming = status === 'streaming'
  const isBusy = isLoading || isExtracting || isStreaming
  const isError = status === 'error'
  const hasSummary = (status === 'done' || status === 'streaming') && summary.length > 0

  const pillActive = 'bg-violet-600/30 text-violet-300 border border-violet-500/40'
  const pillInactive = 'bg-gray-700/40 text-gray-500 border border-gray-700/40 hover:text-gray-300'

  return (
    <div className="flex flex-col gap-3 p-4">
      {/* Mode selector */}
      <div className="flex gap-1.5 flex-wrap">
        {SUMMARY_MODES.map(m => (
          <button
            key={m.id}
            onClick={() => setMode(m.id)}
            className={`px-2.5 py-1 rounded-lg text-[11px] font-medium transition-all
              ${mode === m.id ? pillActive : pillInactive}`}
          >
            {m.label}
          </button>
        ))}

        {/* Custom prompt pills */}
        {customPrompts.map(cp => (
          <button
            key={cp.id}
            onClick={() => setMode(cp.id)}
            className={`group relative px-2.5 py-1 rounded-lg text-[11px] font-medium transition-all pr-5
              ${mode === cp.id ? pillActive : pillInactive}`}
          >
            {cp.label}
            <span
              onClick={e => { e.stopPropagation(); handleDeleteCustomPrompt(cp.id) }}
              className="absolute right-1 top-1/2 -translate-y-1/2 text-gray-500 hover:text-red-400
                         opacity-0 group-hover:opacity-100 transition-opacity cursor-pointer"
            >
              <X size={10} />
            </span>
          </button>
        ))}

        {/* Add custom prompt button */}
        <button
          onClick={() => setShowAddPrompt(!showAddPrompt)}
          className={`px-2 py-1 rounded-lg text-[11px] font-medium transition-all
            ${showAddPrompt
              ? 'bg-violet-600/30 text-violet-300 border border-violet-500/40'
              : 'bg-gray-700/40 text-gray-500 border border-gray-700/40 hover:text-gray-300'
            }`}
          title="Add custom prompt"
        >
          <Plus size={12} />
        </button>
      </div>

      {/* Inline add-custom-prompt form */}
      {showAddPrompt && (
        <div className="flex flex-col gap-2 bg-gray-800/50 border border-gray-700/40 rounded-xl p-3">
          <input
            type="text"
            placeholder="Label (e.g. Technical)"
            value={newLabel}
            onChange={e => setNewLabel(e.target.value)}
            className="w-full rounded-lg px-2.5 py-1.5 text-xs wg-input"
          />
          <textarea
            placeholder="Prompt (e.g. Summarize focusing on technical details...)"
            value={newPromptText}
            onChange={e => setNewPromptText(e.target.value)}
            rows={3}
            className="w-full rounded-lg px-2.5 py-1.5 text-xs wg-input resize-none"
          />
          <button
            onClick={handleAddCustomPrompt}
            disabled={!newLabel.trim() || !newPromptText.trim()}
            className={`self-end px-3 py-1.5 rounded-lg text-[11px] font-semibold transition-all
              ${newLabel.trim() && newPromptText.trim()
                ? 'text-white'
                : 'bg-gray-700/40 text-gray-600 cursor-not-allowed'
              }`}
            style={newLabel.trim() && newPromptText.trim() ? { background: 'var(--accent)' } : undefined}
          >
            Save
          </button>
        </div>
      )}

      {/* Summary length selector */}
      <div className="flex gap-1.5">
        {LENGTH_OPTIONS.map(opt => (
          <button
            key={opt.id}
            onClick={() => onLengthChange(opt.id)}
            className={`px-2.5 py-1 rounded-lg text-[11px] font-medium transition-all
              ${summaryLength === opt.id ? pillActive : pillInactive}`}
          >
            {opt.label}
          </button>
        ))}
      </div>

      {/* Summarize buttons */}
      <div className="flex gap-2">
        <button
          onClick={() => onSummarize(mode)}
          disabled={isBusy || !hasApiKey}
          className={`
            flex items-center justify-center gap-2 flex-1 py-2.5 rounded-xl text-sm font-semibold
            transition-all duration-150
            ${isLoading || isStreaming
              ? 'text-teal-300 cursor-not-allowed'
              : isBusy || !hasApiKey
              ? 'bg-gray-700/60 text-gray-500 cursor-not-allowed'
              : 'text-white shadow-lg'
            }
          `}
          style={
            isLoading || isStreaming
              ? { background: 'var(--accent-muted)' }
              : !(isBusy || !hasApiKey)
              ? { background: 'linear-gradient(to right, var(--grad-from), var(--grad-to))', boxShadow: 'var(--shadow-accent)' }
              : undefined
          }
        >
          {isLoading || isStreaming ? (
            <>
              <span className="w-4 h-4 border-2 border-teal-300/30 border-t-teal-200 rounded-full animate-spin" />
              Summarizing...
            </>
          ) : (
            <>
              <Sparkles size={15} />
              AI Summary
            </>
          )}
        </button>

        <button
          onClick={onExtractPage}
          disabled={isBusy}
          title="Extract full page text — no AI or API key needed"
          className={`
            flex items-center justify-center gap-1.5 px-3 py-2.5 rounded-xl text-sm font-semibold
            transition-all duration-150 flex-shrink-0
            ${isExtracting
              ? 'bg-gray-700/40 text-gray-400 cursor-not-allowed'
              : isBusy
              ? 'bg-gray-700/40 text-gray-600 cursor-not-allowed'
              : 'bg-gray-700/60 hover:bg-gray-600/60 text-gray-300 border border-gray-600/40'
            }
          `}
        >
          {isExtracting ? (
            <>
              <span className="w-3.5 h-3.5 border-2 border-gray-500/30 border-t-gray-300 rounded-full animate-spin" />
              Extracting...
            </>
          ) : (
            <>
              <ScrollText size={14} />
              Full Page
            </>
          )}
        </button>

        <button
          onClick={onMultiTab}
          disabled={isBusy}
          title="Summarize content from multiple tabs"
          className={`
            flex items-center justify-center gap-1.5 px-3 py-2.5 rounded-xl text-sm font-semibold
            transition-all duration-150 flex-shrink-0
            ${isBusy
              ? 'bg-gray-700/40 text-gray-600 cursor-not-allowed'
              : 'bg-gray-700/60 hover:bg-gray-600/60 text-gray-300 border border-gray-600/40'
            }
          `}
        >
          <Layers size={14} />
          Multi-tab
        </button>
      </div>

      {/* No API key hint */}
      {!hasApiKey && (
        <p className="text-gray-600 text-[11px] text-center -mt-1">
          No API key? Use <span className="text-gray-400">Full Page</span> to extract clean page text
        </p>
      )}

      {/* Loading skeleton — only for AI summary loading (not streaming), not Full Page */}
      {isLoading && (
        <div className="flex flex-col gap-2 animate-pulse">
          <div className="h-3 bg-gray-800 rounded-lg w-full" />
          <div className="h-3 bg-gray-800 rounded-lg w-[92%]" />
          <div className="h-3 bg-gray-800 rounded-lg w-[85%]" />
          <div className="h-3 bg-gray-800 rounded-lg w-full" />
          <div className="h-3 bg-gray-800 rounded-lg w-[78%]" />
          <div className="h-3 bg-gray-800 rounded-lg w-[90%]" />
        </div>
      )}

      {/* Error */}
      {isError && (
        <div className="flex items-start gap-2 bg-red-950/30 border border-red-700/30 rounded-xl px-3 py-2.5">
          <AlertCircle size={14} className="text-red-400 mt-0.5 flex-shrink-0" />
          <div>
            <p className="text-red-300 text-xs font-medium">Error generating summary</p>
            <p className="text-red-400/80 text-[11px] mt-0.5 break-words">{errorMessage}</p>
          </div>
        </div>
      )}

      {/* Summary display (done or streaming) */}
      {hasSummary && (
        <div className="relative">
          <div className="flex items-center justify-between mb-2">
            <div className="flex items-center gap-2">
              <h3 className="text-gray-300 text-xs font-semibold uppercase tracking-wider">Summary</h3>
              {isStreaming && (
                <span className="relative flex h-2 w-2">
                  <span className="animate-ping absolute inline-flex h-full w-full rounded-full bg-teal-400 opacity-75" />
                  <span className="relative inline-flex rounded-full h-2 w-2 bg-teal-500" />
                </span>
              )}
              {status === 'done' && (
                <span className="flex items-center gap-1 text-gray-600 text-[10px]">
                  <Clock size={10} />
                  {readingTime(summary)}
                </span>
              )}
              {/* Cached badge */}
              {isCached && status === 'done' && (
                <button
                  onClick={onResync}
                  title="Cached result — click to refresh"
                  className="flex items-center gap-1 px-1.5 py-0.5 rounded-md text-[10px] font-medium
                             bg-amber-900/30 text-amber-400 border border-amber-700/30
                             hover:bg-amber-900/50 transition-colors"
                >
                  <RefreshCw size={9} />
                  Cached
                </button>
              )}
            </div>
            <div className="flex items-center gap-2">
              {/* Compare toggle */}
              {prevSummary && status === 'done' && (
                <button
                  onClick={() => setShowCompare(!showCompare)}
                  title={showCompare ? 'Hide comparison' : 'Compare with previous'}
                  className={`flex items-center gap-1 text-[11px] transition-colors
                    ${showCompare
                      ? 'text-violet-400'
                      : 'text-gray-500 hover:text-gray-200'
                    }`}
                >
                  <ArrowLeftRight size={12} />
                  Compare
                </button>
              )}
              {/* Save to history */}
              <button
                onClick={onSave}
                title={isSaved ? 'Saved to history' : 'Save to history'}
                className={`flex items-center gap-1 text-[11px] transition-colors
                  ${isSaved
                    ? 'text-amber-400'
                    : 'text-gray-500 hover:text-amber-400'
                  }`}
              >
                {isSaved ? <BookmarkCheck size={13} /> : <Bookmark size={13} />}
              </button>
              {/* Copy */}
              <button
                onClick={handleCopy}
                className="flex items-center gap-1 text-gray-500 hover:text-gray-200 text-[11px] transition-colors"
              >
                {copied ? (
                  <>
                    <CheckCheck size={12} className="text-emerald-400" />
                    <span className="text-emerald-400">Copied!</span>
                  </>
                ) : (
                  <>
                    <Copy size={12} />
                    Copy
                  </>
                )}
              </button>
              {/* Copy MD */}
              <button
                onClick={handleCopyMd}
                className="flex items-center gap-1 text-gray-500 hover:text-gray-200 text-[11px] transition-colors"
              >
                {copiedMd ? (
                  <>
                    <CheckCheck size={12} className="text-emerald-400" />
                    <span className="text-emerald-400">Copied!</span>
                  </>
                ) : (
                  <>
                    <FileText size={12} />
                    Copy MD
                  </>
                )}
              </button>
            </div>
          </div>

          {/* Comparison view */}
          {showCompare && prevSummary && status === 'done' ? (
            <div className="flex flex-col gap-2">
              <div className="bg-gray-800/50 border border-gray-700/40 rounded-xl p-3 max-h-40 overflow-y-auto scrollbar-thin">
                <p className="text-gray-500 text-[10px] font-semibold uppercase tracking-wider mb-1.5">Previous</p>
                <div className="text-gray-400 text-sm leading-relaxed whitespace-pre-wrap">
                  {prevSummary}
                </div>
              </div>
              <div className="bg-gray-800/50 border border-violet-700/30 rounded-xl p-3 max-h-40 overflow-y-auto scrollbar-thin">
                <p className="text-violet-400 text-[10px] font-semibold uppercase tracking-wider mb-1.5">Current</p>
                <div className="text-gray-200 text-sm leading-relaxed whitespace-pre-wrap">
                  {summary}
                </div>
              </div>
            </div>
          ) : (
            <div className="bg-gray-800/50 border border-gray-700/40 rounded-xl p-3 max-h-52 overflow-y-auto
                            scrollbar-thin">
              <div className="text-gray-200 text-sm leading-relaxed whitespace-pre-wrap">
                {summary}
                {isStreaming && (
                  <span className="inline-block w-1.5 h-4 bg-teal-400 ml-0.5 animate-pulse rounded-sm align-text-bottom" />
                )}
              </div>
            </div>
          )}
        </div>
      )}
    </div>
  )
}
