export interface PdfExportOptions {
  title: string
  url: string
  summary: string
  translated?: string
  translatedLang?: string
}

function escapeHtml(str: string): string {
  return str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
}

export function exportSummaryAsPdf(options: PdfExportOptions): void {
  const { title, url, summary, translated, translatedLang } = options

  const dateStr = new Date().toLocaleDateString('en-US', {
    year: 'numeric', month: 'long', day: 'numeric',
    hour: '2-digit', minute: '2-digit',
  })

  const html = `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>WebGist — ${escapeHtml(title || 'Summary')}</title>
  <style>
    @media print {
      @page { margin: 15mm; size: A4; }
      body { -webkit-print-color-adjust: exact; print-color-adjust: exact; }
    }
    * { box-sizing: border-box; }
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', 'Noto Sans',
                   'Noto Sans Devanagari', 'Noto Sans Arabic', 'Noto Sans CJK SC',
                   Arial, sans-serif;
      color: #0f172a; margin: 0; padding: 0; line-height: 1.6;
    }
    .header { background: #3b82f6; color: white; padding: 12px 36px; font-size: 14px; font-weight: 700; }
    .content { padding: 28px 36px; }
    .date { color: #64748b; font-size: 11px; margin-bottom: 10px; }
    h1 { font-size: 22px; font-weight: 700; margin: 0 0 5px; color: #0f172a; }
    .url { color: #3b82f6; font-size: 11px; margin-bottom: 22px; word-break: break-all; }
    hr { border: none; border-top: 1px solid #e2e8f0; margin: 18px 0; }
    h2 { font-size: 14px; font-weight: 700; color: #1e293b; margin: 0 0 12px; }
    .text { font-size: 12px; color: #334155; white-space: pre-wrap; line-height: 1.75; }
    .footer { text-align: center; color: #94a3b8; font-size: 10px; margin-top: 32px; }
  </style>
</head>
<body>
  <div class="header">WebGist Summary</div>
  <div class="content">
    <div class="date">Generated: ${dateStr}</div>
    <h1>${escapeHtml(title || 'Untitled Page')}</h1>
    <div class="url">${escapeHtml(url || '')}</div>
    <hr>
    <h2>Summary</h2>
    <div class="text">${escapeHtml(summary)}</div>
    ${translated ? `
      <hr>
      <h2>Translation (${escapeHtml(translatedLang || '')})</h2>
      <div class="text">${escapeHtml(translated)}</div>
    ` : ''}
    <div class="footer">Generated by WebGist</div>
  </div>
</body>
</html>`

  // Store HTML in local storage, open relay page that renders it and triggers print dialog.
  // Must use a separate tab because the popup closes as soon as the print dialog steals focus.
  // active: false keeps the popup open; the export tab loads in background and
  // auto-triggers the print dialog when the user switches to it.
  chrome.storage.local.set({ wg_export: { html } }, () => {
    chrome.tabs.create({ url: chrome.runtime.getURL('export/index.html'), active: true })
  })
}
